### ISSUE TITLE
Issue with Charmbracelet logger

### ISSUE THREAD

**Issue by tburschka** [faabiosr/echo-middleware#17]
After updating my depenencies,  echo middleware is broken. They seem to change something, output from my build pipeline:

    github.com/faabiosr/echo-middleware
    # github.com/faabiosr/echo-middleware
    vendor/github.com/faabiosr/echo-middleware/charm.go:46:12: cannot use charm.Default() (value of type *"github.com/charmbracelet/log".Logger) as "github.com/charmbracelet/log".Logger value in struct literal
    vendor/github.com/faabiosr/echo-middleware/charm.go:63:19: invalid operation: cfg.Logger == nil (mismatched types "github.com/charmbracelet/log".Logger and untyped nil)

**Comment by faabiosr** [comment]
Hi @tburschka thanks for sharing this issue. Looking into [charmbracelet/log](https://github.com/charmbracelet/log/releases) releases it seems they introduce a breaking change next day that I published this new logger 😄 

I am working on the update here. You will have some news soon.

Best.

**Comment by faabiosr** [comment]
A new release was created, please update and share any issues.

https://github.com/faabiosr/echo-middleware/releases/tag/v0.8.1

**Comment by tburschka** [comment]
Works very well, thank you for your fast work!
